CREATE TABLE `door_hanger_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entry_id` varchar(64) NOT NULL,
	`employee_id` varchar(64) NOT NULL,
	`full_name` varchar(255) NOT NULL,
	`date` varchar(16) NOT NULL,
	`city` varchar(128) NOT NULL,
	`area` varchar(255),
	`address` varchar(512) NOT NULL,
	`business_name` varchar(255),
	`outreach_type` enum('door_hangers','business_cards','table_toppers') NOT NULL,
	`quantity_distributed` int NOT NULL,
	`location_type` enum('neighborhood','apartment_complex','business','office','restaurant','retail','other') NOT NULL,
	`contact_person_name` varchar(255),
	`phone_number` varchar(32),
	`email` varchar(320),
	`notes` text,
	`proof_photo_url` text,
	`gps_latitude` decimal(10,6),
	`gps_longitude` decimal(10,6),
	`follow_up_needed` enum('yes','no') NOT NULL DEFAULT 'no',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `door_hanger_entries_id` PRIMARY KEY(`id`),
	CONSTRAINT `door_hanger_entries_entry_id_unique` UNIQUE(`entry_id`)
);
--> statement-breakpoint
CREATE TABLE `door_hanger_follow_ups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`follow_up_id` varchar(64) NOT NULL,
	`entry_id` varchar(64) NOT NULL,
	`employee_id` varchar(64) NOT NULL,
	`business_name` varchar(255) NOT NULL,
	`city` varchar(128) NOT NULL,
	`address` varchar(512) NOT NULL,
	`contact_person_name` varchar(255),
	`outreach_type` enum('door_hangers','business_cards','table_toppers') NOT NULL,
	`original_visit_date` varchar(16) NOT NULL,
	`follow_up_date` varchar(16) NOT NULL,
	`follow_up_type` enum('call','visit','email') NOT NULL,
	`follow_up_notes` text,
	`status` enum('pending','completed','overdue') NOT NULL DEFAULT 'pending',
	`result_notes` text,
	`completed_at` timestamp,
	`new_follow_up_date` varchar(16),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `door_hanger_follow_ups_id` PRIMARY KEY(`id`),
	CONSTRAINT `door_hanger_follow_ups_follow_up_id_unique` UNIQUE(`follow_up_id`)
);
