CREATE TABLE `online_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`booking_id` varchar(64) NOT NULL,
	`location` varchar(128) NOT NULL,
	`first_name` varchar(128) NOT NULL,
	`last_name` varchar(128) NOT NULL,
	`email` varchar(320),
	`phone` varchar(32),
	`street_address` varchar(255),
	`unit` varchar(64),
	`city` varchar(128),
	`state` varchar(64),
	`zip_code` varchar(16),
	`vehicle_type` varchar(64),
	`package_type` varchar(64),
	`selected_addons` text,
	`total_price` decimal(10,2),
	`discount_code` varchar(64),
	`discount_amount` decimal(10,2) DEFAULT '0',
	`final_total` decimal(10,2),
	`booking_date` varchar(16) NOT NULL,
	`time_slot` varchar(64) NOT NULL,
	`start_hour` int,
	`end_hour` int,
	`status` enum('pending','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'confirmed',
	`source_url` varchar(512),
	`zapier_payload` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `online_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `online_bookings_booking_id_unique` UNIQUE(`booking_id`)
);
