CREATE TABLE `schedule_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` varchar(64) NOT NULL,
	`location` varchar(64) NOT NULL,
	`date` varchar(16) NOT NULL,
	`time_slot` varchar(64),
	`start_hour` int,
	`end_hour` int,
	`customer_name` varchar(255),
	`customer_phone` varchar(32),
	`customer_email` varchar(320),
	`vehicle_type` varchar(64),
	`vehicle_color` varchar(64),
	`vehicle_year` varchar(8),
	`vehicle_make` varchar(64),
	`vehicle_model` varchar(64),
	`package_type` varchar(64),
	`service_description` text,
	`selected_addons` text,
	`total_price` decimal(10,2),
	`tips` decimal(10,2) DEFAULT '0',
	`assigned_to` varchar(255),
	`status` enum('pending','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'confirmed',
	`source` enum('manual','online') NOT NULL DEFAULT 'manual',
	`online_booking_id` varchar(64),
	`notes` text,
	`created_by` varchar(64),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `schedule_jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `schedule_jobs_job_id_unique` UNIQUE(`job_id`)
);
