CREATE TABLE `customer_attachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`attachment_id` varchar(64) NOT NULL,
	`customer_name` varchar(255) NOT NULL,
	`customer_phone` varchar(32),
	`customer_email` varchar(320),
	`file_name` varchar(255) NOT NULL,
	`file_url` text NOT NULL,
	`file_key` varchar(512),
	`mime_type` varchar(128),
	`file_size_bytes` int,
	`caption` varchar(512),
	`uploaded_by` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customer_attachments_id` PRIMARY KEY(`id`),
	CONSTRAINT `customer_attachments_attachment_id_unique` UNIQUE(`attachment_id`)
);
--> statement-breakpoint
CREATE TABLE `estimates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estimate_id` varchar(64) NOT NULL,
	`estimate_number` int AUTO_INCREMENT,
	`customer_name` varchar(255) NOT NULL,
	`customer_phone` varchar(32),
	`customer_email` varchar(320),
	`customer_address` varchar(512),
	`vehicle_year` varchar(8),
	`vehicle_make` varchar(64),
	`vehicle_model` varchar(64),
	`vehicle_color` varchar(64),
	`line_items` text NOT NULL,
	`subtotal` decimal(10,2) NOT NULL DEFAULT '0',
	`tax_rate` decimal(5,4) DEFAULT '0',
	`tax_amount` decimal(10,2) DEFAULT '0',
	`discount_amount` decimal(10,2) DEFAULT '0',
	`total` decimal(10,2) NOT NULL DEFAULT '0',
	`status` enum('draft','sent','viewed','accepted','declined','expired') NOT NULL DEFAULT 'draft',
	`notes` text,
	`internal_notes` text,
	`valid_until` varchar(16),
	`sent_at` timestamp,
	`viewed_at` timestamp,
	`responded_at` timestamp,
	`created_by` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `estimates_id` PRIMARY KEY(`id`),
	CONSTRAINT `estimates_estimate_id_unique` UNIQUE(`estimate_id`)
);
