// Training V2 Seed Data — 6 Detailer Modules
// Modules: Welcome & Company Standards, Safety & Chemical Handling,
//          Exterior Detailing, Interior Detailing,
//          Customer Service & Upselling, Using the App

export const trainingV2Modules = [
  {
    moduleId: "TM_WELCOME",
    name: "Welcome & Company Standards",
    description: "Learn who we are, our values, and what it means to represent Luxury Wash On Wheels.",
    icon: "star.fill",
    orderIndex: 1,
  },
  {
    moduleId: "TM_SAFETY",
    name: "Safety & Chemical Handling",
    description: "Proper handling of detailing chemicals, PPE requirements, and job site safety protocols.",
    icon: "shield.fill",
    orderIndex: 2,
  },
  {
    moduleId: "TM_EXTERIOR",
    name: "Exterior Detailing",
    description: "Master the full exterior process including wheels, tires, paint, glass, and trim.",
    icon: "car.fill",
    orderIndex: 3,
  },
  {
    moduleId: "TM_INTERIOR",
    name: "Interior Detailing",
    description: "Deep clean every surface inside the vehicle — seats, carpets, dash, glass, and more.",
    icon: "seat.fill",
    orderIndex: 4,
  },
  {
    moduleId: "TM_CUSTOMER",
    name: "Customer Service & Upselling",
    description: "Deliver a 5-star experience, handle complaints professionally, and grow revenue through upsells.",
    icon: "person.fill",
    orderIndex: 5,
  },
  {
    moduleId: "TM_APP",
    name: "Using the App",
    description: "A complete walkthrough of every feature in the Luxury Wash On Wheels app — your daily operations hub.",
    icon: "iphone",
    orderIndex: 6,
  },
];

export const trainingV2Steps = [
  // ── Module 1: Welcome & Company Standards ──────────────────────────────────
  {
    stepId: "TS_W01",
    moduleId: "TM_WELCOME",
    orderIndex: 1,
    title: "Who We Are",
    description: "Luxury Wash On Wheels is a premium mobile detailing company serving the Niceville and Crestview areas. We bring the detail shop to the customer — showing up on time, doing exceptional work, and leaving every vehicle looking better than new.\n\nOur mission: deliver a 5-star experience every single time, no exceptions.",
    tips: "Take pride in the brand you represent. Customers chose us because of our reputation — protect it.",
  },
  {
    stepId: "TS_W02",
    moduleId: "TM_WELCOME",
    orderIndex: 2,
    title: "Our Core Values",
    description: "1. **Excellence** — We never cut corners. Every step of the process matters.\n2. **Reliability** — Show up on time, every time. If you're running late, notify the customer immediately.\n3. **Integrity** — Be honest with customers and teammates. No shortcuts, no excuses.\n4. **Professionalism** — Clean uniform, clean van, professional communication at all times.\n5. **Teamwork** — Support your teammates. A win for one is a win for all.",
    tips: "These values aren't just words on a wall — they're how we operate every day.",
  },
  {
    stepId: "TS_W03",
    moduleId: "TM_WELCOME",
    orderIndex: 3,
    title: "Appearance & Uniform Standards",
    description: "You are the face of Luxury Wash On Wheels. Customers judge the quality of our work by how we present ourselves.\n\n**Required:**\n- Company polo or t-shirt (clean, no stains)\n- Dark pants or shorts (no ripped jeans)\n- Closed-toe shoes\n- Clean hands and nails before greeting customers\n\n**Not allowed:**\n- Offensive language or imagery on clothing\n- Earbuds/headphones while talking to customers\n- Smoking near customer vehicles",
    warnings: "Showing up in non-uniform or with a dirty appearance reflects poorly on the entire team and can result in a write-up.",
  },
  {
    stepId: "TS_W04",
    moduleId: "TM_WELCOME",
    orderIndex: 4,
    title: "Attendance & Punctuality",
    description: "Your schedule is set in the app. Jobs are assigned to you and customers are expecting you at a specific time.\n\n**Rules:**\n- Be at your first job location by your scheduled start time\n- If you're running late, use the 'Running Late' button in the app BEFORE the appointment time\n- Call-outs must be submitted at least 2 hours before your shift starts\n- Repeated no-shows or late arrivals without notice result in disciplinary action",
    warnings: "Ghosting a customer is one of the most damaging things you can do to the company's reputation. Always communicate.",
    tips: "Set a reminder 30 minutes before each job to give yourself travel time.",
  },
  {
    stepId: "TS_W05",
    moduleId: "TM_WELCOME",
    orderIndex: 5,
    title: "Communication Standards",
    description: "All team communication happens through the app. Here's how to use it:\n\n- **Messages tab**: Team chat and direct messages\n- **Notifications tab**: Company announcements, write-ups, coaching notes\n- **Running Late button**: Automatically texts the customer and notifies admin\n- **Time Off Requests**: Submit through the Schedule tab\n\nDo NOT use personal text messages for work-related communication. Keep everything in the app so there's a record.",
    tips: "Check your notifications every morning before your first job.",
  },

  // ── Module 2: Safety & Chemical Handling ──────────────────────────────────
  {
    stepId: "TS_S01",
    moduleId: "TM_SAFETY",
    orderIndex: 1,
    title: "Personal Protective Equipment (PPE)",
    description: "Before handling any detailing chemical, you must have the right PPE:\n\n- **Nitrile gloves** — Always. No exceptions. Chemicals absorb through skin.\n- **Safety glasses** — Required when spraying any chemical, especially degreasers and wheel cleaners\n- **Respirator/mask** — Required in enclosed spaces (garages) or when using strong solvents\n- **Closed-toe shoes** — Required at all times on the job site\n\nPPE is provided in your van. If you run out, notify your supervisor immediately.",
    warnings: "Never handle iron remover, wheel acid, or engine degreaser without gloves. These chemicals cause chemical burns.",
  },
  {
    stepId: "TS_S02",
    moduleId: "TM_SAFETY",
    orderIndex: 2,
    title: "Chemical Storage & Labeling",
    description: "All chemicals must be:\n\n1. **Stored upright** in the designated chemical cabinet in the van\n2. **Labeled clearly** — never use an unlabeled bottle\n3. **Kept in original containers** or properly labeled spray bottles\n4. **Separated** — acids and alkalines must not be stored together\n5. **Secured** during transport — no loose bottles rolling around\n\nIf a chemical spills in the van, clean it up immediately and report it.",
    warnings: "Mixing chemicals (especially acids and alkalines) can create toxic fumes. Never mix chemicals unless specifically instructed.",
    tips: "Color-code your spray bottles: red = acid (wheel cleaner), blue = alkaline (degreaser), green = neutral (interior cleaner).",
  },
  {
    stepId: "TS_S03",
    moduleId: "TM_SAFETY",
    orderIndex: 3,
    title: "Safe Chemical Application",
    description: "**Wheel Cleaner / Iron Remover:**\n- Apply to cool wheels only (never hot)\n- Do not let it dry on the surface\n- Rinse thoroughly after 2-3 minutes\n\n**Engine Degreaser:**\n- Cover sensitive electronics before applying\n- Do not spray directly on alternator, battery terminals, or air intake\n- Rinse with low-pressure water\n\n**Interior Cleaners:**\n- Test on a hidden area first for leather and fabric\n- Never saturate electronics or screens\n- Ventilate the vehicle when using strong cleaners",
    warnings: "Never use wheel acid on chrome or painted wheels — it will permanently damage the finish.",
  },
  {
    stepId: "TS_S04",
    moduleId: "TM_SAFETY",
    orderIndex: 4,
    title: "Job Site Safety",
    description: "**Traffic Safety:**\n- Park the van to create a buffer between you and traffic\n- Use cones if working near a road\n- Never work in a customer's driveway without their knowledge\n\n**Electrical Safety:**\n- Keep extension cords away from water\n- Inspect cords before each use — no frayed wires\n- Use GFCI outlets when available\n\n**Heat Safety:**\n- Stay hydrated — drink water every 30 minutes in summer\n- Take breaks in the shade\n- Know the signs of heat exhaustion: dizziness, nausea, heavy sweating",
    warnings: "If you feel dizzy or unwell from heat, stop working immediately and move to shade. Notify your supervisor.",
  },
  {
    stepId: "TS_S05",
    moduleId: "TM_SAFETY",
    orderIndex: 5,
    title: "Incident Reporting",
    description: "If anything goes wrong on a job — damage to the vehicle, a chemical spill, a personal injury, or a customer complaint — you must report it immediately.\n\n**How to report:**\n1. Take photos of any damage or incident\n2. Notify your supervisor via the app (message or call)\n3. Do NOT tell the customer you'll 'handle it' without supervisor approval\n4. Fill out an incident report within 24 hours\n\nHonesty is always the right call. Covering up damage makes things much worse.",
    warnings: "Attempting to hide vehicle damage from a customer or supervisor is grounds for immediate termination.",
  },

  // ── Module 3: Exterior Detailing ──────────────────────────────────────────
  {
    stepId: "TS_E01",
    moduleId: "TM_EXTERIOR",
    orderIndex: 1,
    title: "Exterior Process Overview",
    description: "The exterior detail follows a strict top-to-bottom, inside-out order. This prevents cross-contamination and ensures you never re-dirty a surface you've already cleaned.\n\n**Full Exterior Order:**\n1. Pre-rinse\n2. Wheels & tires\n3. Wheel wells\n4. Pre-soak / foam bath\n5. Hand wash (two-bucket method)\n6. Rinse\n7. Door jambs\n8. Dry\n9. Glass (exterior)\n10. Trim & plastic\n11. Final inspection",
    tips: "Always do wheels first — they're the dirtiest part. If you do the paint first, wheel brake dust will contaminate it.",
  },
  {
    stepId: "TS_E02",
    moduleId: "TM_EXTERIOR",
    orderIndex: 2,
    title: "Wheels & Tires",
    description: "**Wheels:**\n1. Spray iron remover on cool wheels — wait 2-3 min until it turns purple\n2. Agitate with a wheel brush (barrel brush for spokes, lug nut brush for holes)\n3. Rinse thoroughly\n4. Apply wheel cleaner if needed for brake dust buildup\n5. Dry with a dedicated wheel towel\n\n**Tires:**\n1. Scrub with a stiff tire brush and all-purpose cleaner\n2. Rinse completely\n3. After the full wash, apply tire dressing (not before — water will dilute it)\n4. Apply dressing with an applicator pad — avoid getting it on the wheel",
    warnings: "Never use iron remover on hot wheels. The chemical reaction can damage the finish.",
    tips: "Use a separate set of brushes and towels for wheels — never use them on paint.",
  },
  {
    stepId: "TS_E03",
    moduleId: "TM_EXTERIOR",
    orderIndex: 3,
    title: "The Two-Bucket Wash Method",
    description: "The two-bucket method prevents swirl marks by keeping your wash mitt clean.\n\n**Setup:**\n- Bucket 1 (Wash): Soapy water with grit guard\n- Bucket 2 (Rinse): Clean water with grit guard\n\n**Process:**\n1. Dip mitt in wash bucket\n2. Wash one panel (top to bottom, side to side)\n3. Rinse mitt in rinse bucket — rub against grit guard to release dirt\n4. Wring out mitt\n5. Dip back in wash bucket\n6. Repeat for each panel\n\nWork in straight lines, not circles. Circular motion creates swirl marks.",
    warnings: "Never drop your wash mitt on the ground. If it falls, get a fresh one — ground debris will scratch the paint.",
    tips: "Work in the shade when possible. Direct sunlight causes soap to dry on the paint before you can rinse it.",
  },
  {
    stepId: "TS_E04",
    moduleId: "TM_EXTERIOR",
    orderIndex: 4,
    title: "Drying & Glass",
    description: "**Drying:**\n1. Use a large microfiber drying towel or waffle-weave towel\n2. Pat dry — do not drag the towel across the paint\n3. Use a detailing spray as a drying aid to reduce friction\n4. Dry door jambs and gas cap area\n5. Blow out water from mirrors, badges, and trim with compressed air or a leaf blower\n\n**Exterior Glass:**\n1. Spray glass cleaner on a microfiber towel (not directly on glass)\n2. Wipe in straight lines\n3. Flip to a dry side and buff to a streak-free finish\n4. Check at an angle in the sunlight for streaks",
    tips: "Two-towel method for glass: one wet towel to clean, one dry towel to buff. This eliminates streaks.",
  },
  {
    stepId: "TS_E05",
    moduleId: "TM_EXTERIOR",
    orderIndex: 5,
    title: "Trim, Plastic & Final Inspection",
    description: "**Exterior Trim & Plastic:**\n1. Apply trim restorer or plastic dressing to black trim\n2. Use an applicator pad — avoid getting product on paint or glass\n3. Wipe off any excess\n\n**Final Inspection:**\n1. Walk around the vehicle slowly\n2. Check for water spots, streaks, missed areas\n3. Check all glass from multiple angles\n4. Ensure tires are dressed evenly\n5. Check door jambs and gas cap\n6. Take before/after photos for the job record",
    tips: "The final inspection is what separates a good detail from a great one. Never skip it.",
  },

  // ── Module 4: Interior Detailing ──────────────────────────────────────────
  {
    stepId: "TS_I01",
    moduleId: "TM_INTERIOR",
    orderIndex: 1,
    title: "Interior Process Overview",
    description: "Interior detailing follows a top-to-bottom order to prevent re-dirtying surfaces.\n\n**Full Interior Order:**\n1. Remove trash and personal items (set aside for customer)\n2. Vacuum headliner (if needed)\n3. Clean upper surfaces: sun visors, overhead console\n4. Dashboard, center console, door panels\n5. Seats (fabric or leather)\n6. Carpets and floor mats\n7. Interior glass\n8. Final wipe-down and inspection\n\nNever move customer belongings without permission. If in doubt, ask.",
    tips: "Start with a dry vacuum before applying any liquid cleaners. Wet dirt is harder to remove than dry dirt.",
  },
  {
    stepId: "TS_I02",
    moduleId: "TM_INTERIOR",
    orderIndex: 2,
    title: "Dashboard & Hard Surfaces",
    description: "**Dashboard, Center Console, Door Panels:**\n1. Use a soft detailing brush to loosen dust from vents, buttons, and crevices\n2. Vacuum out the loosened debris\n3. Apply interior cleaner to a microfiber towel (not directly on surface)\n4. Wipe in sections, working top to bottom\n5. Use a cotton swab or detailing brush for tight areas around buttons\n6. Apply interior dressing to plastic surfaces for a clean, matte finish\n\n**Screens & Electronics:**\n- Use a dedicated screen cleaner and microfiber cloth\n- Never spray liquid directly on screens\n- Wipe gently — no pressure",
    warnings: "Do not use silicone-based dressings on the steering wheel — it makes it slippery and dangerous.",
    tips: "A foam detailing brush works great for AC vents — it gets into every fin without damaging them.",
  },
  {
    stepId: "TS_I03",
    moduleId: "TM_INTERIOR",
    orderIndex: 3,
    title: "Seats — Fabric & Leather",
    description: "**Fabric Seats:**\n1. Vacuum thoroughly with a crevice tool\n2. Pre-treat stains with upholstery cleaner\n3. Agitate with a soft brush\n4. Extract with a wet/dry vac or blot with a microfiber towel\n5. Allow to dry completely before customer pickup\n\n**Leather Seats:**\n1. Vacuum crevices\n2. Apply leather cleaner to a microfiber towel\n3. Wipe in sections — do not scrub aggressively\n4. Buff dry\n5. Apply leather conditioner to prevent cracking\n\n**Always test cleaners on a hidden area first.**",
    warnings: "Never use all-purpose cleaner on leather — it strips the protective coating and causes cracking.",
    tips: "For stubborn fabric stains, let the cleaner dwell for 2-3 minutes before agitating.",
  },
  {
    stepId: "TS_I04",
    moduleId: "TM_INTERIOR",
    orderIndex: 4,
    title: "Carpets & Floor Mats",
    description: "**Floor Mats:**\n1. Remove all floor mats and set outside\n2. Shake out loose debris\n3. Vacuum both sides\n4. Apply carpet cleaner and agitate with a stiff brush\n5. Extract or blot dry\n6. Allow to dry before reinstalling\n\n**Carpet (inside vehicle):**\n1. Vacuum thoroughly — move seats forward and back to reach all areas\n2. Pre-treat stains\n3. Agitate and extract\n4. Check under seats for debris\n\n**Reinstall floor mats correctly** — they must sit flat and not interfere with pedals.",
    warnings: "Wet floor mats reinstalled in the vehicle can cause mold and mildew. Ensure they are dry before putting them back.",
  },
  {
    stepId: "TS_I05",
    moduleId: "TM_INTERIOR",
    orderIndex: 5,
    title: "Interior Glass & Final Inspection",
    description: "**Interior Glass:**\n1. Spray glass cleaner on a microfiber towel\n2. Wipe in straight lines — avoid circular motion\n3. Buff with a dry microfiber to remove streaks\n4. Check windshield from driver's perspective for haze or film\n5. The inside of the windshield often has a greasy film from off-gassing — use a dedicated glass cleaner\n\n**Final Interior Inspection:**\n1. Sit in the driver's seat and look around\n2. Check all vents, buttons, and crevices\n3. Ensure no product residue is left on surfaces\n4. Check that all personal items are returned\n5. Take photos for the job record",
    tips: "The inside of the windshield is often the hardest part to clean streak-free. Use a long-reach applicator pad for the far corners.",
  },

  // ── Module 5: Customer Service & Upselling ────────────────────────────────
  {
    stepId: "TS_C01",
    moduleId: "TM_CUSTOMER",
    orderIndex: 1,
    title: "The Customer Greeting",
    description: "First impressions are everything. When you arrive at a job:\n\n1. Park neatly — do not block the driveway or street\n2. Walk up to the door or greet the customer at the vehicle\n3. Introduce yourself: 'Hi, I'm [Name] from Luxury Wash On Wheels!'\n4. Confirm the service they booked\n5. Do a quick walk-around with the customer to note any pre-existing damage\n6. Take photos of any existing damage before you start\n\nBeing friendly, confident, and professional sets the tone for the entire job.",
    tips: "Smile and make eye contact. Customers want to feel like they can trust you with their vehicle.",
  },
  {
    stepId: "TS_C02",
    moduleId: "TM_CUSTOMER",
    orderIndex: 2,
    title: "During the Job",
    description: "While you're working:\n\n- **Stay focused** — do not be on your phone (except for job-related tasks in the app)\n- **Be visible** — customers appreciate seeing you work hard\n- **Communicate** — if you find something unexpected (heavy staining, damage), let the customer know\n- **Respect their property** — treat their home and vehicle with care\n- **No music with explicit lyrics** — keep it professional\n\nIf the customer asks questions, answer them confidently. If you don't know the answer, say 'Let me check with my supervisor' rather than guessing.",
    tips: "Customers who see you working hard and caring about their vehicle are much more likely to tip and rebook.",
  },
  {
    stepId: "TS_C03",
    moduleId: "TM_CUSTOMER",
    orderIndex: 3,
    title: "Upselling Services",
    description: "Upselling is not pushy sales — it's offering customers services that genuinely benefit them.\n\n**When to upsell:**\n- During the walk-around (before starting)\n- When you discover an issue during the job\n\n**What to say:**\n- 'I noticed your headlights are pretty foggy — we offer headlight restoration for $X. It really improves visibility and the look of the car. Would you like me to add that?'\n- 'Your leather seats are looking a little dry — a conditioning treatment would protect them and keep them soft. It's only $X to add on.'\n\n**Key rule:** Only upsell things that are genuinely needed. Never make up problems.",
    tips: "The best time to upsell is right after the customer sees how good the car looks — they're already happy and more likely to say yes.",
  },
  {
    stepId: "TS_C04",
    moduleId: "TM_CUSTOMER",
    orderIndex: 4,
    title: "Handling Complaints",
    description: "Even when you do everything right, sometimes customers are unhappy. Here's how to handle it:\n\n1. **Listen without interrupting** — let them explain fully\n2. **Acknowledge their concern** — 'I understand, and I want to make this right'\n3. **Do not argue or make excuses**\n4. **Offer a solution** — re-do the area, apply a discount, or escalate to supervisor\n5. **Notify your supervisor** — always loop in management on complaints\n\n**Never:**\n- Argue with a customer\n- Promise a refund without supervisor approval\n- Leave the job site angry",
    warnings: "If a customer becomes aggressive or threatening, do not engage. Remove yourself from the situation and call your supervisor immediately.",
  },
  {
    stepId: "TS_C05",
    moduleId: "TM_CUSTOMER",
    orderIndex: 5,
    title: "Job Completion & Payment",
    description: "When the job is done:\n\n1. Do a final walk-around with the customer\n2. Point out the work you did and highlight the results\n3. Ask: 'Is there anything else I can touch up for you?'\n4. Collect payment through the app\n5. Ask for a Google review: 'If you're happy with the service, a quick Google review would mean a lot to us!'\n6. Thank them by name and let them know you hope to see them again\n\nMark the job as complete in the app before leaving the location.",
    tips: "Customers who do a walk-around with you are far less likely to call with complaints later — they saw the work and approved it.",
  },

  // ── Module 6: Using the App ────────────────────────────────────────────────
  {
    stepId: "TS_A01",
    moduleId: "TM_APP",
    orderIndex: 1,
    title: "Logging In",
    description: "Open the Luxury Wash On Wheels app and enter your Employee ID and 4-digit PIN to log in.\n\nYour Employee ID and PIN were given to you by your supervisor when you were onboarded. If you've forgotten your PIN, contact your supervisor — they can reset it from the admin panel.\n\nOnce logged in, you'll see your role-specific tab bar at the bottom of the screen. Detailers see: Home, Schedule, Messages, Notifications, and Training.",
    tips: "Your PIN is private — do not share it with anyone.",
  },
  {
    stepId: "TS_A02",
    moduleId: "TM_APP",
    orderIndex: 2,
    title: "Your Schedule",
    description: "The **Schedule tab** shows all your jobs for today and upcoming days.\n\nEach job card shows:\n- Customer name and address\n- Service type and vehicle\n- Scheduled time\n- Job status (Scheduled → En Route → In Progress → Finished)\n\n**Updating job status:**\nTap a job card to open the details. Use the status buttons to update as you move through the job. Keeping your status updated helps the office track the fleet in real time.",
    tips: "Update your status as soon as it changes — don't wait until the end of the day.",
  },
  {
    stepId: "TS_A03",
    moduleId: "TM_APP",
    orderIndex: 3,
    title: "Running Late Button",
    description: "If you're running behind on a job, use the **Running Late** button on the job card.\n\n1. Tap the job card to open details\n2. Tap the red 'Running Late' button\n3. Select how many minutes late you'll be (15, 30, 45, 60, or custom)\n4. Review the SMS preview that will be sent to the customer\n5. Tap 'Send Notification'\n\nThis automatically:\n- Texts the customer with your new ETA\n- Notifies the admin team\n- Logs the late notification in the job history\n\nUse this button proactively — customers appreciate advance notice.",
    warnings: "Do NOT call or text customers from your personal phone. Always use the Running Late button in the app.",
  },
  {
    stepId: "TS_A04",
    moduleId: "TM_APP",
    orderIndex: 4,
    title: "Clock In & Clock Out",
    description: "You must clock in and out every day through the app.\n\n**To clock in:**\n1. Go to the Home tab\n2. Tap 'Clock In'\n3. Your clock-in time is recorded\n\n**To clock out:**\n1. Go to the Home tab\n2. Tap 'Clock Out'\n3. Your total hours are calculated automatically\n\n**Breaks:**\nYou are entitled to breaks during your shift. Use the Break buttons on the Home tab to log your breaks. This ensures accurate timesheet records.",
    warnings: "Do not clock in for someone else or have someone clock in for you. This is considered time fraud and is grounds for termination.",
  },
  {
    stepId: "TS_A05",
    moduleId: "TM_APP",
    orderIndex: 5,
    title: "Time Off Requests",
    description: "Need time off? Submit a request through the app.\n\n1. Go to the **Schedule tab**\n2. Tap 'Request Time Off' (or find it in the menu)\n3. Select your start and end dates\n4. Enter the reason for your request\n5. Submit — your supervisor will approve or deny it\n\nYou'll receive a notification when your request is reviewed. Check the **Notifications tab** for updates.\n\n**Policy reminder:** Time off requests must be submitted at least 2 weeks in advance for planned absences. Emergency requests are handled case by case.",
    tips: "The app automatically calculates how many days notice you're giving — the policy requires 14 days for non-emergency requests.",
  },
  {
    stepId: "TS_A06",
    moduleId: "TM_APP",
    orderIndex: 6,
    title: "Messages & Notifications",
    description: "**Messages tab:**\n- Team chat channels (General, Detailers)\n- Direct messages to teammates or supervisors\n- All work communication should happen here — not personal texts\n\n**Notifications tab:**\n- Company announcements\n- Write-ups and coaching notes (require acknowledgment)\n- Time off request updates\n- Job transfer notifications\n- Missed call alerts (admin only)\n\n**Important:** Notifications that require acknowledgment will show a red badge. Tap the notification and tap 'Acknowledge' to confirm you've read it.",
    tips: "Check your notifications every morning. Unacknowledged write-ups or coaching notes can affect your standing.",
  },
  {
    stepId: "TS_A07",
    moduleId: "TM_APP",
    orderIndex: 7,
    title: "Payment & Job Completion",
    description: "When a job is finished:\n\n1. Complete the final inspection\n2. Walk the customer through the work\n3. Tap the job in your Schedule to open it\n4. Tap 'Mark as Finished'\n5. The payment screen will appear — record how the customer paid (cash, card, etc.)\n6. If the customer tips, record the tip amount\n7. Tap 'Save Payment'\n\nThe job will show as complete in the system and the office will be notified.\n\n**Never leave a job without marking it complete and recording payment.**",
    warnings: "Jobs marked as finished but with no payment recorded show a red border in the admin view. Always complete the payment step.",
  },
];

export const trainingV2Questions = [
  // ── Module 1: Welcome & Company Standards ──────────────────────────────────
  {
    questionId: "TQ_W01",
    moduleId: "TM_WELCOME",
    questionText: "What should you do if you're running late to a customer appointment?",
    optionA: "Call the customer from your personal phone",
    optionB: "Use the Running Late button in the app before the appointment time",
    optionC: "Just show up as soon as you can without saying anything",
    optionD: "Ask a teammate to cover for you",
    correctAnswer: "B" as const,
    orderIndex: 1,
  },
  {
    questionId: "TQ_W02",
    moduleId: "TM_WELCOME",
    questionText: "Which of the following is NOT part of the required uniform?",
    optionA: "Company polo or t-shirt",
    optionB: "Closed-toe shoes",
    optionC: "Earbuds while working",
    optionD: "Dark pants or shorts",
    correctAnswer: "C" as const,
    orderIndex: 2,
  },
  {
    questionId: "TQ_W03",
    moduleId: "TM_WELCOME",
    questionText: "Where should all work-related communication happen?",
    optionA: "Personal text messages",
    optionB: "Phone calls only",
    optionC: "The Luxury Wash On Wheels app",
    optionD: "Email",
    correctAnswer: "C" as const,
    orderIndex: 3,
  },
  {
    questionId: "TQ_W04",
    moduleId: "TM_WELCOME",
    questionText: "What is one of Luxury Wash On Wheels' core values?",
    optionA: "Speed over quality",
    optionB: "Reliability — show up on time, every time",
    optionC: "Minimize customer interaction",
    optionD: "Use any products available",
    correctAnswer: "B" as const,
    orderIndex: 4,
  },
  {
    questionId: "TQ_W05",
    moduleId: "TM_WELCOME",
    questionText: "How far in advance must call-outs be submitted before a shift?",
    optionA: "30 minutes",
    optionB: "1 hour",
    optionC: "2 hours",
    optionD: "The night before",
    correctAnswer: "C" as const,
    orderIndex: 5,
  },

  // ── Module 2: Safety & Chemical Handling ──────────────────────────────────
  {
    questionId: "TQ_S01",
    moduleId: "TM_SAFETY",
    questionText: "What PPE is ALWAYS required when handling any detailing chemical?",
    optionA: "Safety glasses only",
    optionB: "Nitrile gloves",
    optionC: "A respirator",
    optionD: "Steel-toed boots",
    correctAnswer: "B" as const,
    orderIndex: 1,
  },
  {
    questionId: "TQ_S02",
    moduleId: "TM_SAFETY",
    questionText: "When should you apply iron remover to wheels?",
    optionA: "When the wheels are hot from driving",
    optionB: "Only on chrome wheels",
    optionC: "When the wheels are cool",
    optionD: "After the full wash is complete",
    correctAnswer: "C" as const,
    orderIndex: 2,
  },
  {
    questionId: "TQ_S03",
    moduleId: "TM_SAFETY",
    questionText: "What should you do if you discover vehicle damage during a job?",
    optionA: "Try to fix it yourself without telling anyone",
    optionB: "Take photos and notify your supervisor immediately",
    optionC: "Tell the customer it was pre-existing damage",
    optionD: "Ignore it and complete the job",
    correctAnswer: "B" as const,
    orderIndex: 3,
  },
  {
    questionId: "TQ_S04",
    moduleId: "TM_SAFETY",
    questionText: "What is the danger of mixing acids and alkaline chemicals?",
    optionA: "They cancel each other out and become ineffective",
    optionB: "They create toxic fumes",
    optionC: "They become too expensive to use",
    optionD: "They stain the vehicle paint",
    correctAnswer: "B" as const,
    orderIndex: 4,
  },
  {
    questionId: "TQ_S05",
    moduleId: "TM_SAFETY",
    questionText: "Which chemical should NEVER be used on chrome or painted wheels?",
    optionA: "Interior cleaner",
    optionB: "Wheel acid",
    optionC: "Tire dressing",
    optionD: "Car wash soap",
    correctAnswer: "B" as const,
    orderIndex: 5,
  },

  // ── Module 3: Exterior Detailing ──────────────────────────────────────────
  {
    questionId: "TQ_E01",
    moduleId: "TM_EXTERIOR",
    questionText: "In the exterior detail process, what should you clean FIRST?",
    optionA: "The paint and body panels",
    optionB: "The windows",
    optionC: "The wheels and tires",
    optionD: "The door jambs",
    correctAnswer: "C" as const,
    orderIndex: 1,
  },
  {
    questionId: "TQ_E02",
    moduleId: "TM_EXTERIOR",
    questionText: "In the two-bucket wash method, what is the purpose of the second (rinse) bucket?",
    optionA: "To hold extra soap",
    optionB: "To rinse the mitt and remove dirt before reloading with soap",
    optionC: "To store clean towels",
    optionD: "To dilute the soap",
    correctAnswer: "B" as const,
    orderIndex: 2,
  },
  {
    questionId: "TQ_E03",
    moduleId: "TM_EXTERIOR",
    questionText: "What motion should you use when washing paint to avoid swirl marks?",
    optionA: "Circular motion",
    optionB: "Random orbital motion",
    optionC: "Straight lines",
    optionD: "Any motion works equally well",
    correctAnswer: "C" as const,
    orderIndex: 3,
  },
  {
    questionId: "TQ_E04",
    moduleId: "TM_EXTERIOR",
    questionText: "When should tire dressing be applied?",
    optionA: "Before the wash to protect the tire",
    optionB: "After the full wash and dry process",
    optionC: "Before rinsing the wheels",
    optionD: "While the tire is still wet",
    correctAnswer: "B" as const,
    orderIndex: 4,
  },
  {
    questionId: "TQ_E05",
    moduleId: "TM_EXTERIOR",
    questionText: "What is the best way to apply glass cleaner to avoid streaks?",
    optionA: "Spray directly on the glass and wipe in circles",
    optionB: "Spray on a microfiber towel and wipe in straight lines",
    optionC: "Use a squeegee and water",
    optionD: "Apply with a sponge",
    correctAnswer: "B" as const,
    orderIndex: 5,
  },

  // ── Module 4: Interior Detailing ──────────────────────────────────────────
  {
    questionId: "TQ_I01",
    moduleId: "TM_INTERIOR",
    questionText: "What is the first step in the interior detailing process?",
    optionA: "Apply interior dressing to the dashboard",
    optionB: "Clean the windows",
    optionC: "Remove trash and vacuum dry debris",
    optionD: "Shampoo the carpets",
    correctAnswer: "C" as const,
    orderIndex: 1,
  },
  {
    questionId: "TQ_I02",
    moduleId: "TM_INTERIOR",
    questionText: "Why should you NEVER use all-purpose cleaner on leather seats?",
    optionA: "It leaves a sticky residue",
    optionB: "It strips the protective coating and causes cracking",
    optionC: "It is too expensive",
    optionD: "It changes the color of the leather",
    correctAnswer: "B" as const,
    orderIndex: 2,
  },
  {
    questionId: "TQ_I03",
    moduleId: "TM_INTERIOR",
    questionText: "Why should you NOT use silicone-based dressing on the steering wheel?",
    optionA: "It smells bad",
    optionB: "It is too expensive",
    optionC: "It makes the wheel slippery and dangerous",
    optionD: "It fades the color",
    correctAnswer: "C" as const,
    orderIndex: 3,
  },
  {
    questionId: "TQ_I04",
    moduleId: "TM_INTERIOR",
    questionText: "Before reinstalling floor mats after cleaning, what must you ensure?",
    optionA: "They are still slightly damp for freshness",
    optionB: "They are completely dry to prevent mold",
    optionC: "They have been treated with carpet protector",
    optionD: "They are placed in the trunk temporarily",
    correctAnswer: "B" as const,
    orderIndex: 4,
  },
  {
    questionId: "TQ_I05",
    moduleId: "TM_INTERIOR",
    questionText: "What is the best approach for cleaning screens and electronics inside the vehicle?",
    optionA: "Spray cleaner directly on the screen and wipe",
    optionB: "Use a damp cloth with water only",
    optionC: "Apply dedicated screen cleaner to a microfiber cloth, then wipe gently",
    optionD: "Avoid cleaning screens entirely",
    correctAnswer: "C" as const,
    orderIndex: 5,
  },

  // ── Module 5: Customer Service & Upselling ────────────────────────────────
  {
    questionId: "TQ_C01",
    moduleId: "TM_CUSTOMER",
    questionText: "What should you do during the customer greeting walk-around?",
    optionA: "Start working immediately to save time",
    optionB: "Note and photograph any pre-existing damage with the customer present",
    optionC: "Ask the customer to wait inside",
    optionD: "Skip it if you're running late",
    correctAnswer: "B" as const,
    orderIndex: 1,
  },
  {
    questionId: "TQ_C02",
    moduleId: "TM_CUSTOMER",
    questionText: "When is the BEST time to offer an upsell to a customer?",
    optionA: "After they've already paid",
    optionB: "During the walk-around before starting, or when you discover a genuine issue",
    optionC: "Only if they ask about additional services",
    optionD: "Never — upselling is too pushy",
    correctAnswer: "B" as const,
    orderIndex: 2,
  },
  {
    questionId: "TQ_C03",
    moduleId: "TM_CUSTOMER",
    questionText: "A customer is unhappy with the job. What should you do FIRST?",
    optionA: "Argue your case and explain why they're wrong",
    optionB: "Offer a refund immediately",
    optionC: "Listen without interrupting and acknowledge their concern",
    optionD: "Leave the job site",
    correctAnswer: "C" as const,
    orderIndex: 3,
  },
  {
    questionId: "TQ_C04",
    moduleId: "TM_CUSTOMER",
    questionText: "After completing a job, what should you ask the customer?",
    optionA: "Nothing — just collect payment and leave",
    optionB: "If they want to schedule another appointment right now",
    optionC: "If there's anything else you can touch up, and ask for a Google review",
    optionD: "If they want to tip",
    correctAnswer: "C" as const,
    orderIndex: 4,
  },
  {
    questionId: "TQ_C05",
    moduleId: "TM_CUSTOMER",
    questionText: "What should you do if a customer becomes aggressive or threatening?",
    optionA: "Stand your ground and defend yourself verbally",
    optionB: "Remove yourself from the situation and call your supervisor",
    optionC: "Offer a full refund to calm them down",
    optionD: "Continue working and ignore them",
    correctAnswer: "B" as const,
    orderIndex: 5,
  },
];
