// Comprehensive training content based on the Luxury Wash handbook

export const trainingModulesData = [
  {
    moduleId: "MOD_001",
    name: "Engine Bay",
    description: "Learn how to properly clean the engine bay",
    icon: "wrench",
    videoUrl: "https://www.loom.com/embed/a8b0b7b40db94ef68748c76bf62a3ee7",
    orderIndex: 1,
  },
  {
    moduleId: "MOD_002",
    name: "Wheels",
    description: "Master wheel cleaning techniques",
    icon: "wheel",
    orderIndex: 2,
  },
  {
    moduleId: "MOD_003",
    name: "Tires",
    description: "Proper tire cleaning and treatment",
    icon: "tire",
    orderIndex: 3,
  },
  {
    moduleId: "MOD_004",
    name: "Wheel Wells",
    description: "Clean wheel wells thoroughly",
    icon: "circle",
    orderIndex: 4,
  },
  {
    moduleId: "MOD_005",
    name: "Exhaust Tips",
    description: "Polish and clean exhaust tips",
    icon: "spark",
    orderIndex: 5,
  },
  {
    moduleId: "MOD_006",
    name: "Door Jambs & Gas Cap",
    description: "Detail door jambs and gas cap",
    icon: "door",
    orderIndex: 6,
  },
  {
    moduleId: "MOD_007",
    name: "Bug Removal",
    description: "Remove bugs from front-end",
    icon: "bug",
    orderIndex: 7,
  },
  {
    moduleId: "MOD_008",
    name: "Tar/Sap Removal",
    description: "Remove tar and tree sap safely",
    icon: "droplet",
    orderIndex: 8,
  },
  {
    moduleId: "MOD_009",
    name: "Headliner",
    description: "Clean interior headliner",
    icon: "roof",
    orderIndex: 9,
  },
  {
    moduleId: "MOD_010",
    name: "Door Panels & Dash",
    description: "Clean door panels and dashboard",
    icon: "panel",
    orderIndex: 10,
  },
  {
    moduleId: "MOD_011",
    name: "Cup Holders",
    description: "Detail cup holders",
    icon: "cup",
    orderIndex: 11,
  },
  {
    moduleId: "MOD_012",
    name: "Final Blow & Wipe",
    description: "Final interior finishing touches",
    icon: "wind",
    orderIndex: 12,
  },
  {
    moduleId: "MOD_013",
    name: "Window Cleaning",
    description: "Clean all windows to perfection",
    icon: "window",
    orderIndex: 13,
  },
  {
    moduleId: "MOD_014",
    name: "Dressing",
    description: "Apply tire and plastic dressing",
    icon: "sparkles",
    orderIndex: 14,
  },
];

export const trainingToolsData = [
  // Engine Bay Tools
  { toolId: "TOOL_001", moduleId: "MOD_001", name: "Degreaser Dressing", description: "For degreasing engine surfaces", orderIndex: 1 },
  { toolId: "TOOL_002", moduleId: "MOD_001", name: "Detail Brush", description: "For scrubbing detailed areas", orderIndex: 2 },
  { toolId: "TOOL_003", moduleId: "MOD_001", name: "All-Purpose Towel", description: "For wiping and drying", orderIndex: 3 },

  // Wheels Tools
  { toolId: "TOOL_004", moduleId: "MOD_002", name: "Wheel Brush", description: "Specialized brush for wheel cleaning", orderIndex: 1 },
  { toolId: "TOOL_005", moduleId: "MOD_002", name: "Brake Buster Brush", description: "For brake dust removal", orderIndex: 2 },
  { toolId: "TOOL_006", moduleId: "MOD_002", name: "Pressure Washer", description: "High-pressure water cleaning", orderIndex: 3 },
  { toolId: "TOOL_007", moduleId: "MOD_002", name: "Wash Mitt", description: "For gentle wheel washing", orderIndex: 4 },

  // Tires Tools
  { toolId: "TOOL_008", moduleId: "MOD_003", name: "Tire Brush", description: "Stiff brush for tire scrubbing", orderIndex: 1 },
  { toolId: "TOOL_009", moduleId: "MOD_003", name: "Pressure Washer", description: "For rinsing tires", orderIndex: 2 },
  { toolId: "TOOL_010", moduleId: "MOD_003", name: "All-Purpose Towel", description: "For drying", orderIndex: 3 },

  // Wheel Wells Tools
  { toolId: "TOOL_011", moduleId: "MOD_004", name: "Wheel Well Brush", description: "Specialized brush for wheel wells", orderIndex: 1 },
  { toolId: "TOOL_012", moduleId: "MOD_004", name: "Pressure Washer", description: "For high-pressure cleaning", orderIndex: 2 },
  { toolId: "TOOL_013", moduleId: "MOD_004", name: "Green Brush", description: "For scrubbing wheel wells", orderIndex: 3 },

  // Exhaust Tips Tools
  { toolId: "TOOL_014", moduleId: "MOD_005", name: "Acid (for chrome)", description: "For polishing chrome exhaust tips", orderIndex: 1 },
  { toolId: "TOOL_015", moduleId: "MOD_005", name: "Detail Brush", description: "For scrubbing", orderIndex: 2 },
  { toolId: "TOOL_016", moduleId: "MOD_005", name: "All-Purpose Towel", description: "For polishing", orderIndex: 3 },

  // Door Jambs & Gas Cap Tools
  { toolId: "TOOL_017", moduleId: "MOD_006", name: "Detail Brush", description: "For detailed areas", orderIndex: 1 },
  { toolId: "TOOL_018", moduleId: "MOD_006", name: "All-Purpose Towel", description: "For wiping", orderIndex: 2 },
  { toolId: "TOOL_019", moduleId: "MOD_006", name: "Interior Cleaner", description: "For cleaning surfaces", orderIndex: 3 },

  // Bug Removal Tools
  { toolId: "TOOL_020", moduleId: "MOD_007", name: "Bug Sponge", description: "Specialized sponge for bug removal", orderIndex: 1 },
  { toolId: "TOOL_021", moduleId: "MOD_007", name: "Bug Off", description: "Chemical for dissolving bug residue", orderIndex: 2 },
  { toolId: "TOOL_022", moduleId: "MOD_007", name: "Plastic Blade Sap", description: "For scraping dried bugs", orderIndex: 3 },

  // Tar/Sap Removal Tools
  { toolId: "TOOL_023", moduleId: "MOD_008", name: "Solvent Remover", description: "Chemical solvent for tar and sap", orderIndex: 1 },
  { toolId: "TOOL_024", moduleId: "MOD_008", name: "Plastic Blade Sap", description: "For scraping tar and sap", orderIndex: 2 },
  { toolId: "TOOL_025", moduleId: "MOD_008", name: "All-Purpose Towel", description: "For wiping", orderIndex: 3 },

  // Headliner Tools
  { toolId: "TOOL_026", moduleId: "MOD_009", name: "Interior Cleaner", description: "For headliner cleaning", orderIndex: 1 },
  { toolId: "TOOL_027", moduleId: "MOD_009", name: "Ninja Pad", description: "Soft pad for gentle cleaning", orderIndex: 2 },
  { toolId: "TOOL_028", moduleId: "MOD_009", name: "All-Purpose Towel", description: "For drying", orderIndex: 3 },

  // Door Panels & Dash Tools
  { toolId: "TOOL_029", moduleId: "MOD_010", name: "Interior Cleaner", description: "For cleaning surfaces", orderIndex: 1 },
  { toolId: "TOOL_030", moduleId: "MOD_010", name: "Scrub Ninja", description: "Interior detail brush", orderIndex: 2 },
  { toolId: "TOOL_031", moduleId: "MOD_010", name: "All-Purpose Towel", description: "For wiping", orderIndex: 3 },

  // Cup Holders Tools
  { toolId: "TOOL_032", moduleId: "MOD_011", name: "Detail Brush", description: "For reaching into cup holders", orderIndex: 1 },
  { toolId: "TOOL_033", moduleId: "MOD_011", name: "Interior Cleaner", description: "For cleaning", orderIndex: 2 },
  { toolId: "TOOL_034", moduleId: "MOD_011", name: "All-Purpose Towel", description: "For drying", orderIndex: 3 },

  // Final Blow & Wipe Tools
  { toolId: "TOOL_035", moduleId: "MOD_012", name: "Tornado", description: "Air blower for final drying", orderIndex: 1 },
  { toolId: "TOOL_036", moduleId: "MOD_012", name: "All-Purpose Towel", description: "For final wipe down", orderIndex: 2 },

  // Window Cleaning Tools
  { toolId: "TOOL_037", moduleId: "MOD_013", name: "Window Cleaner", description: "Glass cleaning solution", orderIndex: 1 },
  { toolId: "TOOL_038", moduleId: "MOD_013", name: "Window Cleaning Towel", description: "Lint-free towel for windows", orderIndex: 2 },
  { toolId: "TOOL_039", moduleId: "MOD_013", name: "Window Polish Towel", description: "For final polishing", orderIndex: 3 },

  // Dressing Tools
  { toolId: "TOOL_040", moduleId: "MOD_014", name: "Tire Dressing", description: "For tire shine and protection", orderIndex: 1 },
  { toolId: "TOOL_041", moduleId: "MOD_014", name: "Tire Dressing Applicator Pad", description: "For applying tire dressing", orderIndex: 2 },
  { toolId: "TOOL_042", moduleId: "MOD_014", name: "Dark Blue Dressing Towel", description: "For wiping excess dressing", orderIndex: 3 },
  { toolId: "TOOL_043", moduleId: "MOD_014", name: "White Dressing", description: "For plastic trim protection", orderIndex: 4 },
];

export const trainingStepsData = [
  // Engine Bay Steps
  {
    stepId: "STEP_001",
    moduleId: "MOD_001",
    orderIndex: 1,
    title: "Remove Engine Cover",
    description: "Carefully remove the plastic engine cover if accessible. Set it aside in a safe location.",
    warnings: "Do not force the cover - check for clips or fasteners first",
    tips: "Take a photo before removing to remember placement",
  },
  {
    stepId: "STEP_002",
    moduleId: "MOD_001",
    orderIndex: 2,
    title: "Apply Degreaser",
    description: "Spray degreaser dressing evenly across all engine surfaces. Let it sit for 2-3 minutes to break down grease and grime.",
    warnings: "Avoid spraying directly on electrical components",
    tips: "Work from top to bottom so degreaser flows downward",
  },
  {
    stepId: "STEP_003",
    moduleId: "MOD_001",
    orderIndex: 3,
    title: "Scrub with Detail Brush",
    description: "Use the detail brush to scrub all surfaces, paying special attention to corners and crevices where dirt accumulates.",
    warnings: "Be gentle around hoses and belts",
    tips: "Use circular motions for best results",
  },
  {
    stepId: "STEP_004",
    moduleId: "MOD_001",
    orderIndex: 4,
    title: "Rinse Thoroughly",
    description: "Rinse the entire engine bay with water. Use low pressure to avoid damaging components.",
    warnings: "Do not use high-pressure water directly on electrical parts",
    tips: "Rinse from top to bottom to ensure all degreaser is removed",
  },
  {
    stepId: "STEP_005",
    moduleId: "MOD_001",
    orderIndex: 5,
    title: "Dry and Wipe",
    description: "Use all-purpose towels to dry the engine bay completely. Replace the engine cover if it was removed.",
    warnings: "Make sure everything is dry before closing the hood",
    tips: "Use multiple towels if needed to prevent water spots",
  },

  // Wheels Steps
  {
    stepId: "STEP_006",
    moduleId: "MOD_002",
    orderIndex: 1,
    title: "Pre-rinse Wheels",
    description: "Use pressure washer to remove loose dirt and brake dust from wheel surfaces.",
    warnings: "Keep pressure washer at safe distance to avoid damage",
    tips: "Start with lower pressure and increase as needed",
  },
  {
    stepId: "STEP_007",
    moduleId: "MOD_002",
    orderIndex: 2,
    title: "Apply Wheel Cleaner",
    description: "Spray wheel cleaner on all wheel surfaces and let it sit for 1-2 minutes to break down brake dust.",
    warnings: "Do not let cleaner dry on the wheel",
    tips: "Work on one wheel at a time for best results",
  },
  {
    stepId: "STEP_008",
    moduleId: "MOD_002",
    orderIndex: 3,
    title: "Scrub with Wheel Brush",
    description: "Use wheel brush to scrub all surfaces including the barrel and back of the wheel. Use brake buster brush for stubborn brake dust.",
    warnings: "Do not scrub too hard as it may scratch the wheel",
    tips: "Pay special attention to the inner barrel where brake dust accumulates",
  },
  {
    stepId: "STEP_009",
    moduleId: "MOD_002",
    orderIndex: 4,
    title: "Rinse Thoroughly",
    description: "Rinse all wheels completely with pressure washer to remove all cleaner and debris.",
    warnings: "Ensure all soap residue is removed",
    tips: "Rinse the wheel well area as well",
  },
  {
    stepId: "STEP_010",
    moduleId: "MOD_002",
    orderIndex: 5,
    title: "Dry Wheels",
    description: "Use all-purpose towels to dry wheels completely to prevent water spots.",
    warnings: "Water spots can permanently damage wheel finish",
    tips: "Dry the barrel and back of the wheel thoroughly",
  },

  // Tires Steps
  {
    stepId: "STEP_011",
    moduleId: "MOD_003",
    orderIndex: 1,
    title: "Rinse Tires",
    description: "Use pressure washer to rinse tires and remove loose dirt.",
    warnings: "Keep pressure moderate to avoid damaging tire",
    tips: "Work on one tire at a time",
  },
  {
    stepId: "STEP_012",
    moduleId: "MOD_003",
    orderIndex: 2,
    title: "Apply Tire Cleaner",
    description: "Spray tire cleaner on all tire surfaces and let sit for 1-2 minutes.",
    warnings: "Do not let cleaner dry on tire",
    tips: "Ensure even coverage on all sides",
  },
  {
    stepId: "STEP_013",
    moduleId: "MOD_003",
    orderIndex: 3,
    title: "Scrub with Tire Brush",
    description: "Use stiff tire brush to scrub all tire surfaces including sidewalls and tread.",
    warnings: "Scrub firmly but do not damage the tire",
    tips: "Use circular motions for even cleaning",
  },
  {
    stepId: "STEP_014",
    moduleId: "MOD_003",
    orderIndex: 4,
    title: "Rinse Clean",
    description: "Rinse tires completely to remove all cleaner and dirt.",
    warnings: "Ensure all soap is removed",
    tips: "Rinse multiple times if needed",
  },
  {
    stepId: "STEP_015",
    moduleId: "MOD_003",
    orderIndex: 5,
    title: "Dry Tires",
    description: "Use all-purpose towels to dry tires completely.",
    warnings: "Tires must be dry before applying dressing",
    tips: "Dry sidewalls thoroughly",
  },

  // Wheel Wells Steps
  {
    stepId: "STEP_016",
    moduleId: "MOD_004",
    orderIndex: 1,
    title: "Pre-rinse Wheel Well",
    description: "Use pressure washer to remove loose dirt and debris from wheel well.",
    warnings: "Be careful not to spray directly into brake components",
    tips: "Start with lower pressure",
  },
  {
    stepId: "STEP_017",
    moduleId: "MOD_004",
    orderIndex: 2,
    title: "Apply Wheel Well Cleaner",
    description: "Spray wheel well cleaner and let it sit for 1-2 minutes to break down grime.",
    warnings: "Avoid electrical components",
    tips: "Ensure even coverage",
  },
  {
    stepId: "STEP_018",
    moduleId: "MOD_004",
    orderIndex: 3,
    title: "Scrub Thoroughly",
    description: "Use wheel well brush and green brush to scrub all surfaces inside the wheel well.",
    warnings: "Be careful around suspension components",
    tips: "Pay attention to corners and crevices",
  },
  {
    stepId: "STEP_019",
    moduleId: "MOD_004",
    orderIndex: 4,
    title: "Rinse Clean",
    description: "Rinse wheel well completely with pressure washer.",
    warnings: "Ensure all cleaner is removed",
    tips: "Rinse multiple times if needed",
  },
  {
    stepId: "STEP_020",
    moduleId: "MOD_004",
    orderIndex: 5,
    title: "Dry Wheel Well",
    description: "Use towels to dry accessible areas of the wheel well.",
    warnings: "Some areas may not be fully accessible",
    tips: "Use air blower if available for hard-to-reach areas",
  },

  // Exhaust Tips Steps
  {
    stepId: "STEP_021",
    moduleId: "MOD_005",
    orderIndex: 1,
    title: "Cool Down Check",
    description: "Ensure exhaust tips are cool before touching. Wait at least 30 minutes after driving.",
    warnings: "Hot exhaust tips can cause severe burns",
    tips: "Touch the tip lightly with your hand to check temperature",
  },
  {
    stepId: "STEP_022",
    moduleId: "MOD_005",
    orderIndex: 2,
    title: "Apply Acid Cleaner",
    description: "Spray acid cleaner on exhaust tips and let sit for 2-3 minutes to dissolve oxidation.",
    warnings: "Wear gloves and avoid skin contact",
    tips: "Work in a well-ventilated area",
  },
  {
    stepId: "STEP_023",
    moduleId: "MOD_005",
    orderIndex: 3,
    title: "Scrub with Detail Brush",
    description: "Use detail brush to scrub exhaust tips, working out oxidation and discoloration.",
    warnings: "Do not scrub too hard as it may scratch chrome",
    tips: "Use circular motions for best results",
  },
  {
    stepId: "STEP_024",
    moduleId: "MOD_005",
    orderIndex: 4,
    title: "Rinse Thoroughly",
    description: "Rinse exhaust tips completely to remove all acid cleaner.",
    warnings: "Ensure all acid is removed to prevent damage",
    tips: "Rinse multiple times",
  },
  {
    stepId: "STEP_025",
    moduleId: "MOD_005",
    orderIndex: 5,
    title: "Polish and Dry",
    description: "Use all-purpose towel to polish and dry exhaust tips to a shine.",
    warnings: "Make sure tips are completely dry",
    tips: "Use circular polishing motions for best shine",
  },

  // Door Jambs & Gas Cap Steps
  {
    stepId: "STEP_026",
    moduleId: "MOD_006",
    orderIndex: 1,
    title: "Open All Doors",
    description: "Open all doors, trunk, and gas cap to access jambs and surfaces.",
    warnings: "Be careful not to hit the door against the car",
    tips: "Open doors fully to access all areas",
  },
  {
    stepId: "STEP_027",
    moduleId: "MOD_006",
    orderIndex: 2,
    title: "Spray Interior Cleaner",
    description: "Spray interior cleaner on all door jambs and gas cap area.",
    warnings: "Avoid spraying on paint",
    tips: "Let cleaner sit for 1-2 minutes",
  },
  {
    stepId: "STEP_028",
    moduleId: "MOD_006",
    orderIndex: 3,
    title: "Scrub with Detail Brush",
    description: "Use detail brush to scrub all jambs, hinges, and gas cap area.",
    warnings: "Be careful around hinges",
    tips: "Pay attention to corners where dirt accumulates",
  },
  {
    stepId: "STEP_029",
    moduleId: "MOD_006",
    orderIndex: 4,
    title: "Wipe Clean",
    description: "Use all-purpose towels to wipe all areas clean and dry.",
    warnings: "Ensure all cleaner is removed",
    tips: "Use multiple towels if needed",
  },
  {
    stepId: "STEP_030",
    moduleId: "MOD_006",
    orderIndex: 5,
    title: "Final Check",
    description: "Close all doors and gas cap. Inspect for any missed spots.",
    warnings: "Make sure everything is properly closed",
    tips: "Check all jambs are clean and dry",
  },

  // Bug Removal Steps
  {
    stepId: "STEP_031",
    moduleId: "MOD_007",
    orderIndex: 1,
    title: "Pre-rinse Front End",
    description: "Rinse the front bumper, hood, and headlights with water to loosen bugs.",
    warnings: "Use gentle pressure to avoid paint damage",
    tips: "Let water soak for a minute to soften dried bugs",
  },
  {
    stepId: "STEP_032",
    moduleId: "MOD_007",
    orderIndex: 2,
    title: "Apply Bug Off",
    description: "Spray bug off solution on affected areas and let sit for 2-3 minutes.",
    warnings: "Do not let solution dry on paint",
    tips: "Reapply if needed for stubborn bugs",
  },
  {
    stepId: "STEP_033",
    moduleId: "MOD_007",
    orderIndex: 3,
    title: "Use Bug Sponge",
    description: "Gently use bug sponge to remove dissolved bug residue. Do not scrub hood with bug sponge.",
    warnings: "DO NOT SCRUB HOOD WITH BUG SPONGE - it will damage paint",
    tips: "Use gentle circular motions on bumper and headlights",
  },
  {
    stepId: "STEP_034",
    moduleId: "MOD_007",
    orderIndex: 4,
    title: "Use Plastic Blade for Stubborn Bugs",
    description: "For remaining bugs, use plastic blade sap tool at a shallow angle to gently scrape.",
    warnings: "Be very careful not to scratch paint",
    tips: "Use light pressure and let the blade do the work",
  },
  {
    stepId: "STEP_035",
    moduleId: "MOD_007",
    orderIndex: 5,
    title: "Rinse and Dry",
    description: "Rinse front end thoroughly and dry with all-purpose towels.",
    warnings: "Ensure all bug off solution is removed",
    tips: "Check for any remaining bugs and repeat if needed",
  },

  // Tar/Sap Removal Steps
  {
    stepId: "STEP_036",
    moduleId: "MOD_008",
    orderIndex: 1,
    title: "Identify Tar and Sap Spots",
    description: "Inspect the vehicle for tar and sap spots, typically found on lower body panels and hood.",
    warnings: "Do not attempt to remove with pressure washer",
    tips: "Feel the paint to locate sticky spots",
  },
  {
    stepId: "STEP_037",
    moduleId: "MOD_008",
    orderIndex: 2,
    title: "Apply Solvent Remover",
    description: "Apply solvent remover to tar and sap spots and let sit for 2-3 minutes to dissolve.",
    warnings: "Use in well-ventilated area - fumes can be strong",
    tips: "Reapply if needed for thick deposits",
  },
  {
    stepId: "STEP_038",
    moduleId: "MOD_008",
    orderIndex: 3,
    title: "Use Plastic Blade Carefully",
    description: "Use plastic blade sap tool at a shallow angle to gently remove dissolved tar and sap.",
    warnings: "Be very careful not to scratch paint",
    tips: "Let the solvent do the work - do not force",
  },
  {
    stepId: "STEP_039",
    moduleId: "MOD_008",
    orderIndex: 4,
    title: "Wipe Clean",
    description: "Wipe all areas with all-purpose towels to remove residue and solvent.",
    warnings: "Ensure all solvent is removed",
    tips: "Use multiple towels if needed",
  },
  {
    stepId: "STEP_040",
    moduleId: "MOD_008",
    orderIndex: 5,
    title: "Final Inspection",
    description: "Inspect for any remaining tar or sap and repeat process if necessary.",
    warnings: "Do not leave solvent on paint",
    tips: "Check in sunlight for best visibility",
  },

  // Headliner Steps
  {
    stepId: "STEP_041",
    moduleId: "MOD_009",
    orderIndex: 1,
    title: "Vacuum Interior First",
    description: "Vacuum the interior to remove loose dirt and dust before cleaning headliner.",
    warnings: "Be careful not to damage upholstery",
    tips: "Use upholstery attachment",
  },
  {
    stepId: "STEP_042",
    moduleId: "MOD_009",
    orderIndex: 2,
    title: "Apply Interior Cleaner",
    description: "Spray interior cleaner on headliner in light mist. Do not oversaturate.",
    warnings: "Do not soak the headliner - it can damage the material",
    tips: "Start with light application",
  },
  {
    stepId: "STEP_043",
    moduleId: "MOD_009",
    orderIndex: 3,
    title: "Gently Wipe with Ninja Pad",
    description: "Use ninja pad to gently wipe headliner in circular motions. Do not scrub hard.",
    warnings: "Headliner material is delicate - use gentle pressure",
    tips: "Work in sections from front to back",
  },
  {
    stepId: "STEP_044",
    moduleId: "MOD_009",
    orderIndex: 4,
    title: "Wipe Dry",
    description: "Use all-purpose towels to wipe headliner dry and remove any remaining cleaner.",
    warnings: "Ensure headliner is not too wet",
    tips: "Use light pressure to avoid damaging material",
  },
  {
    stepId: "STEP_045",
    moduleId: "MOD_009",
    orderIndex: 5,
    title: "Air Dry",
    description: "Leave doors and windows open to allow headliner to air dry completely.",
    warnings: "Do not close vehicle until headliner is dry",
    tips: "This usually takes 30-60 minutes",
  },

  // Door Panels & Dash Steps
  {
    stepId: "STEP_046",
    moduleId: "MOD_010",
    orderIndex: 1,
    title: "Vacuum Door Panels",
    description: "Vacuum door panels and dashboard to remove loose dirt and dust.",
    warnings: "Be careful around delicate controls",
    tips: "Use upholstery attachment",
  },
  {
    stepId: "STEP_047",
    moduleId: "MOD_010",
    orderIndex: 2,
    title: "Apply Interior Cleaner",
    description: "Spray interior cleaner on door panels and dashboard. Do not oversaturate.",
    warnings: "Avoid spraying on electronics and screens",
    tips: "Let cleaner sit for 1-2 minutes",
  },
  {
    stepId: "STEP_048",
    moduleId: "MOD_010",
    orderIndex: 3,
    title: "Scrub with Scrub Ninja",
    description: "Use scrub ninja detail brush to gently scrub door panels and dashboard.",
    warnings: "Be careful around buttons and controls",
    tips: "Use gentle circular motions",
  },
  {
    stepId: "STEP_049",
    moduleId: "MOD_010",
    orderIndex: 4,
    title: "Wipe Clean",
    description: "Use all-purpose towels to wipe all surfaces clean and dry.",
    warnings: "Ensure all cleaner is removed from electronics",
    tips: "Use multiple towels if needed",
  },
  {
    stepId: "STEP_050",
    moduleId: "MOD_010",
    orderIndex: 5,
    title: "Final Detail",
    description: "Inspect for any missed spots and ensure all surfaces are clean and dry.",
    warnings: "Check around air vents and crevices",
    tips: "Use detail brush for hard-to-reach areas",
  },

  // Cup Holders Steps
  {
    stepId: "STEP_051",
    moduleId: "MOD_011",
    orderIndex: 1,
    title: "Remove Debris",
    description: "Remove any loose debris, crumbs, or trash from cup holders.",
    warnings: "Be careful not to damage cup holder",
    tips: "Use a small brush or vacuum attachment",
  },
  {
    stepId: "STEP_052",
    moduleId: "MOD_011",
    orderIndex: 2,
    title: "Apply Interior Cleaner",
    description: "Spray interior cleaner into cup holders and let sit for 1-2 minutes.",
    warnings: "Do not oversaturate",
    tips: "Ensure cleaner reaches all areas",
  },
  {
    stepId: "STEP_053",
    moduleId: "MOD_011",
    orderIndex: 3,
    title: "Scrub with Detail Brush",
    description: "Use detail brush to scrub inside cup holders, reaching all corners and crevices.",
    warnings: "Be careful not to damage cup holder material",
    tips: "Use small circular motions",
  },
  {
    stepId: "STEP_054",
    moduleId: "MOD_011",
    orderIndex: 4,
    title: "Wipe Dry",
    description: "Use all-purpose towels to wipe cup holders dry.",
    warnings: "Ensure no moisture remains",
    tips: "Use a cloth wrapped around your finger for tight spots",
  },
  {
    stepId: "STEP_055",
    moduleId: "MOD_011",
    orderIndex: 5,
    title: "Final Inspection",
    description: "Inspect cup holders for cleanliness and ensure they are completely dry.",
    warnings: "Check for any remaining debris",
    tips: "Cup holders should shine and be spotless",
  },

  // Final Blow & Wipe Steps
  {
    stepId: "STEP_056",
    moduleId: "MOD_012",
    orderIndex: 1,
    title: "Use Tornado Air Blower",
    description: "Use tornado air blower to blow out dust and debris from all interior surfaces.",
    warnings: "Wear safety glasses to protect from flying debris",
    tips: "Start from top and work downward",
  },
  {
    stepId: "STEP_057",
    moduleId: "MOD_012",
    orderIndex: 2,
    title: "Blow Out Vents and Crevices",
    description: "Pay special attention to air vents, cup holders, and other crevices where dust settles.",
    warnings: "Be careful not to blow dust into electronics",
    tips: "Use controlled bursts of air",
  },
  {
    stepId: "STEP_058",
    moduleId: "MOD_012",
    orderIndex: 3,
    title: "Vacuum Any Remaining Dust",
    description: "Vacuum any dust that may have settled on seats and floor.",
    warnings: "Use gentle suction to avoid damage",
    tips: "Pay attention to floor mats and under seats",
  },
  {
    stepId: "STEP_059",
    moduleId: "MOD_012",
    orderIndex: 4,
    title: "Final Wipe Down",
    description: "Use all-purpose towels to wipe any missed spots and ensure interior is clean.",
    warnings: "Do not leave any dust or debris",
    tips: "Check all surfaces one final time",
  },
  {
    stepId: "STEP_060",
    moduleId: "MOD_012",
    orderIndex: 5,
    title: "Close Doors and Windows",
    description: "Close all doors and windows. Interior should be spotless.",
    warnings: "Make sure nothing was left inside",
    tips: "Take a final look before closing",
  },

  // Window Cleaning Steps
  {
    stepId: "STEP_061",
    moduleId: "MOD_013",
    orderIndex: 1,
    title: "Roll Down Windows Partially",
    description: "Roll windows down about 1/3 of the way. Use window cleaner and towel to clean the top edge.",
    warnings: "Be careful not to get cleaner on paint",
    tips: "This prevents streaks on the window frame",
  },
  {
    stepId: "STEP_062",
    moduleId: "MOD_013",
    orderIndex: 2,
    title: "Roll Windows Back Up",
    description: "Roll windows back up to their normal position.",
    warnings: "Make sure windows are fully closed",
    tips: "Check that windows seal properly",
  },
  {
    stepId: "STEP_063",
    moduleId: "MOD_013",
    orderIndex: 3,
    title: "Spray Window Cleaner",
    description: "Spray windows generously with window cleaner solution.",
    warnings: "Do not oversaturate",
    tips: "Work on one window at a time",
  },
  {
    stepId: "STEP_064",
    moduleId: "MOD_013",
    orderIndex: 4,
    title: "Wipe with Cleaning Towel",
    description: "Use window cleaning towel to wipe windows in circular motions until clean.",
    warnings: "Use lint-free towel to avoid streaks",
    tips: "Apply firm pressure for best results",
  },
  {
    stepId: "STEP_065",
    moduleId: "MOD_013",
    orderIndex: 5,
    title: "Polish with Polish Towel",
    description: "Spray a light mist of window cleaner and polish with window polish towel for streak-free shine.",
    warnings: "Use light pressure to avoid streaks",
    tips: "This final step ensures crystal clear windows",
  },

  // Dressing Steps
  {
    stepId: "STEP_066",
    moduleId: "MOD_014",
    orderIndex: 1,
    title: "Prepare Tire Dressing",
    description: "Spray tire dressing applicator pad with tire dressing. Make sure tip of sprayer touches the pad.",
    warnings: "Do not oversaturate the pad",
    tips: "Use light spray bursts",
  },
  {
    stepId: "STEP_067",
    moduleId: "MOD_014",
    orderIndex: 2,
    title: "Apply to Tires",
    description: "Apply tire dressing to the entire front of each tire using the applicator pad.",
    warnings: "Ensure even coverage",
    tips: "Work on one tire at a time",
  },
  {
    stepId: "STEP_068",
    moduleId: "MOD_014",
    orderIndex: 3,
    title: "Wipe Down Tires",
    description: "Use dark blue dressing towel to wipe down tires and ensure NO SLING (excess dressing flying off).",
    warnings: "Excess dressing will sling onto the vehicle - wipe thoroughly",
    tips: "This is critical to prevent customer complaints",
  },
  {
    stepId: "STEP_069",
    moduleId: "MOD_014",
    orderIndex: 4,
    title: "Apply White Dressing",
    description: "Apply white dressing to any exterior plastics including trim, bumpers, and side skirts.",
    warnings: "Do not apply to paint",
    tips: "Use light application for best results",
  },
  {
    stepId: "STEP_070",
    moduleId: "MOD_014",
    orderIndex: 5,
    title: "Final Inspection",
    description: "Inspect tires for shine and ensure no excess dressing is present. Check plastic trim for even coverage.",
    warnings: "Make sure there is no sling on the vehicle",
    tips: "Vehicle should look showroom ready",
  },
];
